import { z } from "zod";
import { MESSAGE_MAX_LENGTH, MESSAGE_PAGE_SIZE } from "./types";

/**
 * Input schemas for every messaging operation (CLAUDE.md §9.3). The same schema
 * validates in the service; the composer uses the length limit for its counter.
 */

const uuid = z.uuid({ error: "Not a valid identifier." });

export const searchPeopleSchema = z.object({
  query: z.string().trim().min(1).max(100),
});

export const openDirectConversationSchema = z.object({
  userId: uuid,
});

export const sendMessageSchema = z.object({
  conversationId: uuid,
  /** Generated by the sending client; makes a retried send idempotent. */
  clientMessageId: uuid,
  content: z
    .string()
    .trim()
    .min(1, "Write a message first.")
    .max(MESSAGE_MAX_LENGTH, `Messages are limited to ${MESSAGE_MAX_LENGTH} characters.`),
});

export const listMessagesSchema = z.object({
  conversationId: uuid,
  /** Return messages older than this message. */
  before: uuid.optional(),
  /** Return messages newer than this message. Ignored when `before` is set. */
  after: uuid.optional(),
  limit: z.number().int().min(1).max(100).default(MESSAGE_PAGE_SIZE),
});

export const markReadSchema = z.object({
  conversationId: uuid,
  /** The newest message the reader has seen. */
  messageId: uuid,
});

export const conversationIdSchema = z.object({ conversationId: uuid });
